### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by expilo** [jpinon/larswm#2]
http://verplant.org/larswm/ http://verplant.org/larswm-xinerama.shtml  is down. BTW, why links are plain text and not links?

**Comment by quite** [comment]
For me, verplant.org actually works. But there are other sites related to larswm that are down, like fnurt.net. So I would not be surprised if availability in general is intermittent. larswm is not maintained, and I did not use it myself for about 7 years.

Hm, I even don't see where you found those links :)

**Comment by jpinon** [comment]
I am not linked to verplant.org.

I tried to clarify the purpose of this repo in a new README.
